# -*- coding: utf-8 -*-
"""HH_Izhikevich.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F-v_tQQMOqfnP_YZ_3myuQ_nJXRdj1CG
"""

import os, warnings
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
warnings.filterwarnings('ignore')

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from scipy.integrate import solve_ivp
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

plt.rcParams.update({'figure.dpi': 120, 'font.size': 11})

"""---
## 1  The Full Hodgkin-Huxley Model

$$C_m \frac{dV}{dt} = I - \underbrace{g_{\text{Na}} m^3 h (V - E_{\text{Na}})}_{\text{Na}^+} - \underbrace{g_K n^4 (V - E_K)}_{\text{K}^+} - \underbrace{g_L (V - E_L)}_{\text{leak}}$$

Each gating variable $x \in \{m, h, n\}$ obeys:
$$\frac{dx}{dt} = \alpha_x(V)(1-x) - \beta_x(V)x = \frac{x_\infty(V) - x}{\tau_x(V)}$$
"""

# ── Membrane and conductance parameters ──────────────────────────────────────
C_m  = 1.0    # µF/cm²
g_Na = 120.0  # mS/cm²
g_K  = 36.0
g_L  = 0.3
E_Na = 50.0   # mV
E_K  = -77.0
E_L  = -54.387

# ── Voltage-dependent rate functions ─────────────────────────────────────────
def alpha_m(V): return 0.1*(V + 40) / (1 - np.exp(-(V + 40)/10))
def beta_m(V):  return 4.0 * np.exp(-(V + 65)/18)
def alpha_h(V): return 0.07 * np.exp(-(V + 65)/20)
def beta_h(V):  return 1.0 / (1 + np.exp(-(V + 35)/10))
def alpha_n(V): return 0.01*(V + 55) / (1 - np.exp(-(V + 55)/10))
def beta_n(V):  return 0.125 * np.exp(-(V + 65)/80)

def x_inf(alpha, beta, V): return alpha(V) / (alpha(V) + beta(V))
def tau_x(alpha, beta, V): return 1.0  / (alpha(V) + beta(V))

# ── Hodgkin-Huxley ODE system ─────────────────────────────────────────────────
def hh_ode(t, y, I_ext):
    V, m, h, n = y
    I_Na = g_Na * m**3 * h * (V - E_Na)
    I_K  = g_K  * n**4     * (V - E_K)
    I_L  = g_L             * (V - E_L)
    dV = (I_ext - I_Na - I_K - I_L) / C_m
    dm = alpha_m(V)*(1-m) - beta_m(V)*m
    dh = alpha_h(V)*(1-h) - beta_h(V)*h
    dn = alpha_n(V)*(1-n) - beta_n(V)*n
    return [dV, dm, dh, dn]

# ── Simulate ──────────────────────────────────────────────────────────────────
V0  = -65.0
y0  = [V0,
       x_inf(alpha_m, beta_m, V0),
       x_inf(alpha_h, beta_h, V0),
       x_inf(alpha_n, beta_n, V0)]
t   = np.arange(0, 100, 0.01)

sol = solve_ivp(hh_ode, (0, 100), y0, method='RK45',
                t_eval=t, max_step=0.025, args=(10.0,))
V_hh, m_hh, h_hh, n_hh = sol.y

fig, axes = plt.subplots(2, 1, figsize=(10, 5), sharex=True)
axes[0].plot(t, V_hh, 'k', lw=1.2)
axes[0].set_ylabel('V (mV)'); axes[0].set_title('Hodgkin–Huxley simulation  (I = 10 µA/cm²)')
axes[1].plot(t, m_hh, label='m (fast)')
axes[1].plot(t, h_hh, label='h (slow)')
axes[1].plot(t, n_hh, label='n (slow)')
axes[1].set_xlabel('Time (ms)'); axes[1].set_ylabel('Gate value')
axes[1].legend(ncol=3)
plt.tight_layout(); plt.show()

"""---
## 2  Timescale Separation  →  Quasi-Static Approximation for $m$

If $\tau_m \ll \tau_n, \tau_h$ everywhere, then $m$ equilibrates almost instantaneously and we can replace the ODE for $m$ with the algebraic constraint $m = m_\infty(V)$. This drops the dimension from 4 to 3.
"""

V_r = np.linspace(-80, 40, 500)
tm  = tau_x(alpha_m, beta_m, V_r)
tn  = tau_x(alpha_n, beta_n, V_r)
th  = tau_x(alpha_h, beta_h, V_r)

print(f"τ_m  [{tm.min():.3f}, {tm.max():.3f}] ms   ← fast")
print(f"τ_n  [{tn.min():.3f}, {tn.max():.3f}] ms")
print(f"τ_h  [{th.min():.3f}, {th.max():.3f}] ms")
print(f"\nmean τ_n / τ_m ≈ {np.mean(tn)/np.mean(tm):.0f}×  →  m ≈ m_∞(V)  is valid")

fig, ax = plt.subplots(figsize=(8, 3.5))
ax.semilogy(V_r, tm, label=r'$\tau_m$ (fast)', lw=2)
ax.semilogy(V_r, tn, label=r'$\tau_n$', lw=2)
ax.semilogy(V_r, th, label=r'$\tau_h$', lw=2)
ax.set_xlabel('V (mV)'); ax.set_ylabel('Time constant (ms, log)')
ax.set_title('Gate timescales — justifying the quasi-static approximation')
ax.legend(); plt.tight_layout(); plt.show()

"""---
## 3  Phase-Plane Reduction to 2D

With $m \approx m_\infty(V)$ the system is 3D: $(V, h, n)$. A further standard reduction notes that $h$ and $n$ are strongly anti-correlated during spiking (Rinzel 1985):  $h \approx 0.89 - 1.1n$. We therefore keep just one slow variable

$$u \equiv n  \quad (\text{proxy for adaptation / recovery})$$

giving the 2D system:
$$\frac{dV}{dt} = f(V) - u + I, \qquad \frac{du}{dt} = \varepsilon\,(b V - u)$$

The $V$-nullcline is the set of points where $\dot V = 0$, i.e., $u = f(V) + I$.
"""

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

# Left: h–n anti-correlation
axes[0].scatter(n_hh[::10], h_hh[::10], s=2, alpha=0.3, c=t[::10], cmap='viridis')
axes[0].set_xlabel('n  (K⁺ gate)'); axes[0].set_ylabel('h  (Na⁺ inactivation)')
axes[0].set_title('h–n anti-correlation (Rinzel reduction)')

# Right: V–n phase portrait (the 2D projection we keep)
axes[1].plot(V_hh[::5], n_hh[::5], lw=0.5, alpha=0.6, color='steelblue')
axes[1].set_xlabel('V (mV)'); axes[1].set_ylabel('n')
axes[1].set_title('Phase portrait: the V–n plane')

plt.tight_layout(); plt.show()

"""---
## 4  Taylor Expansion Around the Saddle-Node Bifurcation

We expand $f(V)$ around the bifurcation point $V_0$ (where the neuron first begins to fire). At a **saddle-node bifurcation**:

$$f'(V_0) = 0 \quad \Longrightarrow \quad \text{the linear term vanishes}$$

Keeping only the quadratic remainder:

$$f(V) \approx f(V_0) + \frac{f''(V_0)}{2}(V - V_0)^2$$

Substituting into $u = f(V) + I$ and collecting powers:

$$\boxed{u = c_0 + c_1 V + c_2 V^2}$$

with $c_2 = f''(V_0)/2 > 0$ (the curvature that gives the parabolic nullcline).

In the canonical Izhikevich parameterization this becomes $0.04V^2 + 5V + 140$, obtained by shifting and rescaling to match real neuron data.

---
## 5  Fit the Quadratic Nullcline to HH Data

We treat the HH trajectory as "ground truth" and fit $n \approx c_0 + c_1 V + c_2 V^2$ using ordinary least squares — this recovers the Izhikevich coefficients **directly from biophysics**, no free parameters.
"""

# Steady-state nullcline: set dV/dt = 0 with all gates at steady state
V_grid = np.linspace(-80, 40, 500)
m_ss = x_inf(alpha_m, beta_m, V_grid)
h_ss = x_inf(alpha_h, beta_h, V_grid)
n_ss = x_inf(alpha_n, beta_n, V_grid)

u_nullcline = (g_Na * m_ss**3 * h_ss * (V_grid - E_Na)
             + g_K  * n_ss**4        * (V_grid - E_K)
             + g_L                   * (V_grid - E_L))

X = np.column_stack([V_grid, V_grid**2])
reg = LinearRegression().fit(X, u_nullcline)
c0 = reg.intercept_
c1, c2 = reg.coef_
R2 = reg.score(X, u_nullcline)

print(f"c₀ = {c0:+.4f}  c₁ = {c1:+.4f}  c₂ = {c2:+.4f}  R² = {R2:.4f}")

fig, ax = plt.subplots(figsize=(8, 4))
ax.scatter(V_grid, u_nullcline, s=3, alpha=0.4, label='HH nullcline', zorder=3)
ax.plot(V_grid, c0 + c1*V_grid + c2*V_grid**2, 'r', lw=2, label=f'Quadratic fit  (R²={R2:.3f})')
ax.set_xlabel('V (mV)'); ax.set_ylabel('I_ionic (µA/cm²)')
ax.set_title('V-nullcline: steady-state HH vs quadratic approximation')
ax.legend()
plt.tight_layout(); plt.show()

"""---
## 6  The Izhikevich Model

Replacing $f(V)$ with the fitted parabola and writing $u$ as a combined recovery variable yields the **Izhikevich (2003) model**:

$$\frac{dv}{dt} = 0.04v^2 + 5v + 140 - u + I$$
$$\frac{du}{dt} = a\,(bv - u)$$

with reset rule: **if** $v \geq 30$ mV, **then** $v \leftarrow c$, $u \leftarrow u + d$.

| Parameter | Role |
|-----------|------|
| $a$ | Recovery time scale |
| $b$ | Coupling of $u$ to $v$ |
| $c$ | After-spike reset voltage |
| $d$ | After-spike recovery jump |

Different $(a, b, c, d)$ tuples reproduce RS, IB, CH, FS, LTS, RZ, and TC firing patterns.
"""

# ── Rescale fitted HH nullcline to Izhikevich form ───────────────────────────
# Canonical Izhikevich: 0.04v² + 5v + 140
# Our fit:              c2*V² + c1*V + c0
# Scale factor k = c2 / 0.04  →  divide all coefficients by k, rescale v

k_scale = c2 / 0.04
a2 = c2 / k_scale          # → 0.04
a1 = c1 / k_scale          # → ~5
a0 = c0 / k_scale          # → ~140

print("Rescaled Izhikevich nullcline coefficients:")
print(f"  a2 (should be ~0.04) = {a2:.4f}")
print(f"  a1 (should be ~5)    = {a1:.4f}")
print(f"  a0 (should be ~140)  = {a0:.4f}")
print(f"\n  Scale factor k = {k_scale:.4f}")
print(f"  Canonical:  0.04v² + 5v + 140")
print(f"  Derived:    {a2:.4f}v² + {a1:.4f}v + {a0:.4f}")

# ── Izhikevich model with derived nullcline ───────────────────────────────────
def izhikevich(a, b, c_reset, d, I_ext=10, T=200, dt=0.1):
    t = np.arange(0, T, dt)
    v = np.full(len(t), -65.0)
    u = np.full(len(t), b * -65.0)
    spikes = []
    for i in range(1, len(t)):
        # ODE uses derived a2, a1, a0 instead of hardcoded 0.04, 5, 140
        v[i] = v[i-1] + dt*(a2*v[i-1]**2 + a1*v[i-1] + a0 - u[i-1] + I_ext)
        u[i] = u[i-1] + dt*(a*(b*v[i-1] - u[i-1]))
        if v[i] >= 30:
            v[i-1] = 30
            v[i]   = c_reset
            u[i]  += d
            spikes.append(t[i])
    return t, v, u, spikes

neuron_types = {
    'Regular Spiking (RS)':        dict(a=0.02, b=0.2,  c_reset=-65, d=8),
    'Intrinsically Bursting (IB)': dict(a=0.02, b=0.2,  c_reset=-55, d=4),
    'Fast Spiking (FS)':           dict(a=0.1,  b=0.2,  c_reset=-65, d=2),
    'Low-Threshold Spiking (LTS)': dict(a=0.02, b=0.25, c_reset=-65, d=2),
}

fig, axes = plt.subplots(2, 2, figsize=(13, 7), sharex=True)
for ax, (name, params) in zip(axes.flat, neuron_types.items()):
    t_iz, v_iz, u_iz, spks = izhikevich(**params)
    ax.plot(t_iz, v_iz, 'k', lw=0.9)
    ax.set_title(name, fontsize=10)
    ax.set_ylabel('v (mV)')
    ax.set_ylim(-90, 45)
    fr = len(spks) / 0.2 if spks else 0
    ax.text(0.97, 0.97, f'{fr:.0f} Hz', transform=ax.transAxes,
            ha='right', va='top', fontsize=9, color='steelblue')
for ax in axes[1]:
    ax.set_xlabel('Time (ms)')
fig.suptitle(f'Izhikevich model — derived from HH fit\n(a2={a2:.4f}, a1={a1:.4f}, a0={a0:.4f})',
             fontsize=11)
plt.tight_layout(); plt.show()

# ── Side-by-side comparison ───────────────────────────────────────────────────
t_iz, v_iz, _, _ = izhikevich(0.02, 0.2, -65, 8, I_ext=10, T=100)

fig, axes = plt.subplots(2, 1, figsize=(11, 5), sharex=True)
axes[0].plot(t, V_hh, 'k', lw=1.2, label='Hodgkin–Huxley (4D)')
axes[0].set_ylabel('V (mV)'); axes[0].legend(loc='upper right'); axes[0].set_ylim(-85, 60)
axes[1].plot(t_iz, v_iz, color='firebrick', lw=1.2,
             label=f'Izhikevich — derived (a2={a2:.3f}, a1={a1:.3f}, a0={a0:.2f})')
axes[1].set_ylabel('v (mV)'); axes[1].set_xlabel('Time (ms)')
axes[1].legend(loc='upper right'); axes[1].set_ylim(-85, 60)
fig.suptitle('HH vs Izhikevich derived from HH nullcline fit', fontsize=11)
plt.tight_layout(); plt.show()

"""---
## 7  Summary of the Derivation

| Step | Operation | Dimension |
|------|-----------|:---------:|
| Full HH model | 4 ODEs: $V, m, h, n$ | 4D |
| Quasi-static $m$ | $m \approx m_\infty(V)$, remove ODE | 3D |
| Rinzel reduction | $h \approx \phi(n)$, merge slow gates into $u$ | 2D |
| Taylor at bifurcation | $f(V) \approx c_0 + c_1 V + c_2 V^2$ (linear term = 0) | 2D |
| Izhikevich model | $\dot v = 0.04v^2 + 5v + 140 - u + I$ | 2D |

The reset rule $(v \leftarrow c,\ u \leftarrow u+d)$ mimics the fast Na⁺ inactivation and K⁺ recovery that HH handles through explicit gate dynamics — giving back the spiking behaviour without the computational cost.
"""

# ── Summary ───────────────────────────────────────────────────────────────────
print("=" * 55)
print("DERIVATION SUMMARY")
print("=" * 55)
print(f"{'Step':<35} {'Dim':>4}")
print("-" * 55)
print(f"{'Full HH model':<35} {'4D':>4}")
print(f"{'Quasi-static m → m∞(V)':<35} {'3D':>4}")
print(f"{'Rinzel: h ≈ φ(n)':<35} {'2D':>4}")
print(f"{'Taylor expand at bifurcation':<35} {'2D':>4}")
print("-" * 55)
print(f"\nFitted nullcline (HH units):")
print(f"  u = {c0:.2f} + {c1:.4f}·V + {c2:.4f}·V²   R²={R2:.4f}")
print(f"\nRescaled (Izhikevich units):")
print(f"  u = {a0:.2f} + {a1:.4f}·v + {a2:.4f}·v²")
print(f"\nCanonical Izhikevich:")
print(f"  u = 140   + 5·v      + 0.04·v²")

